version: "3.9"

services:
  order_manager:
    build: ./ordermanager
    ports:
      - "8000:8000"
    depends_on:
      - kafka
      - redis

  order_state_resolver:
    build: ./orderstateresolver
    depends_on:
      - kafka
      - redis

  redis-master:
    build:
      context: ./redis
      dockerfile: Dockerfile.master
    container_name: redis-master
    ports:
      - "6379:6379"
    volumes:
      - redis-master-data:/data

  redis-slave:
    build:
      context: ./redis
      dockerfile: Dockerfile.slave
    container_name: redis-slave
    ports:
      - "6380:6379"
    environment:
      - REDIS_MASTER_SERVICE_HOST=redis-master
    volumes:
      - redis-slave-data:/data

  kafka:
    image: "confluentinc/cp-kafka:latest"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    depends_on:
      - zookeeper

  zookeeper:
    image: "confluentinc/cp-zookeeper:latest"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

volumes:
  redis-master-data:
  redis-slave-data:
